--
-- BayouGuru's Top CPU/RAM Conky
-- Plasma 6 Wayland Edition
--

conky.config = {

out_to_x = false,
out_to_wayland = true,
update_interval = 1,
total_run_times = 0,
disable_auto_reload = true,

alignment = "top_left",
gap_x = 0,
gap_y = 734,

minimum_width = 260,
maximum_width = 260,
minimum_height = 289,

own_window_type = "normal",
own_window_title = "Tops-Conky",
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
own_window_colour = "cc000000",

double_buffer = true,
text_buffer_size = 256,
no_buffers = false,

use_xft = true,
font = "Andersans:bold:size=10",

short_units = true,
temperature_unit = "fahrenheit",

forced_redraw = false,

draw_outline = false,
draw_shades = true,
draw_borders = false,

border_inner_margin = 0,
border_outer_margin = 0,
border_width = 1,

default_outline_color = "333333",
default_color = "212121",
default_shade_color = "070707",

color0 = '111111',
color1 = 'lightblue',
color2 = 'orange',
color3 = 'goldenrod1',
color4 = 'white',
color5 = 'SteelBlue',

template0 = '${font Andersans:bold:size=10}',
template1 = '${color1}${font Andersans:bold:size=10}',
template2 = '${color5}${font Arial:size=10}',
template3 = '${goto 41}${color5}${font Arial:size=10}',

lua_load = '/home/bayouguru/.conky/Wayland/tops_wayland.lua',
lua_draw_hook_pre = 'conky_draw_pre'
}

conky.text = [[${color4}Processes   ${color1}Active ${color2}${running_processes}${goto 188}${color1}Total ${color2}${alignr}${processes}
${template2}┌${color4}${template0}RAM Usage ${color5}${hr 1}
${template2}├${color2}${template0}${top_mem name 1}${alignr 3}${top_mem pid 1}${alignr}${top_mem mem 1}${color1}%
${template2}├${color2}${template0}${top_mem name 2}${alignr 3}${top_mem pid 2}${alignr}${top_mem mem 2}${color1}%
${template2}├${color2}${template0}${top_mem name 3}${alignr 3}${top_mem pid 3}${alignr}${top_mem mem 3}${color1}%
${template2}├${color2}${template0}${top_mem name 4}${alignr 3}${top_mem pid 4}${alignr}${top_mem mem 4}${color1}%
${template2}├${color2}${template0}${top_mem name 5}${alignr 3}${top_mem pid 5}${alignr}${top_mem mem 5}${color1}%
${template2}┌${color4}${template0}CPU Usage ${color5}${hr 1}
${template2}├${color2}${template0}${top name 1}${alignr 3}${top pid 1}${alignr}${top cpu 1}${color1}%
${template2}├${color2}${template0}${top name 2}${alignr 3}${top pid 2}${alignr}${top cpu 2}${color1}%
${template2}├${color2}${template0}${top name 3}${alignr 3}${top pid 3}${alignr}${top cpu 3}${color1}%
${template2}├${color2}${template0}${top name 4}${alignr 3}${top pid 4}${alignr}${top cpu 4}${color1}%
${template2}├${color2}${template0}${top name 5}${alignr 3}${top pid 5}${alignr}${top cpu 5}${color1}%
${template2}├${color2}${template0}${top name 6}${alignr 3}${top pid 6}${alignr}${top cpu 6}${color1}%
${template2}├${color2}${template0}${top name 7}${alignr 3}${top pid 7}${alignr}${top cpu 7}${color1}%
${template2}├${color2}${template0}${top name 8}${alignr 3}${top pid 8}${alignr}${top cpu 8}${color1}%
${template2}├${color2}${template0}${top name 9}${alignr 3}${top pid 9}${alignr}${top cpu 9}${color1}%
${template2}└${color2}${template0}${top name 10}${alignr 3}${top pid 10}${alignr}${top cpu 10}${color1}%
]]
