--  BayouGuru's Network/Right Conky!
--  version:  2026-07-22 (Wayland, SVG background)
--

conky.config = {
out_to_x = false,
out_to_wayland = true,

update_interval = 1,
net_avg_samples = 2,
total_run_times = 0,
disable_auto_reload = true,

alignment = "top_right",
gap_x = 0,
gap_y = 0,
minimum_width = 260,
maximum_width = 260,
minimum_height = 1026,

own_window_title = "Net-Conky",
own_window_type = "override",
own_window_hints = "undecorated,below,sticky,skip_taskbar,skip_pager",
own_window_colour = "CC000000",

double_buffer = true,
show_graph_scale = false,
no_buffers = false,
pad_percents = 1,

font = "Andersans:bold:size=11",
text_buffer_size = 1024,
short_units = true,
temperature_unit = "fahrenheit",
forced_redraw = false,

draw_graph_borders = false,
draw_outline = false,
draw_shades = true,
draw_borders = false,
border_inner_margin = 0,
border_outer_margin = 0,
border_width = 0,

default_outline_color = "000000",
default_color = "212121",
default_shade_color = "070707",

color0 = '111111',
color1 = 'lightblue',
color2 = 'orange',
color3 = 'goldenrod1',
color4 = 'white',
color5 = 'SteelBlue',
color6 = 'yellow',

template0 = '${goto 2}${font Andersans:bold:size=11}',
template1 = '${color1}${font Andersans:bold:size=10}',
template2 = '${font Andersans:bold:size=10}',
template3 = '${font NimbusSansNarrow-Regular:size=10}',
template4 = '${color5}${font Arial:bold:size=10}',

-- Pass the SVG path to Lua
lua_load = '/home/bayouguru/.conky/Wayland/updownbars-wayland.lua',
lua_draw_hook_pre = 'conky_draw_pre',
lua_draw_hook_post = 'conky_draw_post',
}
conky.text = [[${color4}Versions${font}${color5} ${hr 1}
${template4}├${template1} OS${color3}${alignr}Kubuntu ${execi 43200 lsb_release -d | awk '{print $3,$4}'}
${template4}├${template1} Plasma${color3}${alignr}${execi 43200 plasmashell --version | sed 's/\plasmashell //g'}
${template4}├${template1} Kernel${color3}${alignr}${execi 43200 uname -r | sed -e 's/-generic//'}
${template4}├${template1} X.org${color3}${alignr}${execi 43200 xdpyinfo | grep version: | cut -d' ' -f3}
${template4}├${template1} GPU${color3}${alignr}${execi 43200 glxinfo | grep "OpenGL version" |cut -c52-70}
${template4}├${template1} PipeWire${color3}${alignr}${execi 43200 pipewire --version | awk 'NR==2{print $NF}'}
${template4}└${template1} Conky${color3}${alignr}${conky_version}
${color4}Network${font}${color5} ${hr 1}
${template4}├${template1} LAN v4 IP${color3}${alignr 4}${template2}${addr enp7s0}
${template4}├${template1} WAN v4 IP${color3}${alignr 4}${template2}${execi 300 curl --max-time 1 --connect-timeout 1 ifconfig.me}
${template4}├${template1} MAC${color3}${alignr 3}${template2}${execi 360 ip link show enp7s0 | awk '/ether/ {print $2}'}
${template4}├${template1} Hostname${template2}${color3}${alignr 4}${nodename}
${template4}├${color1}↑${color2}${template2}${upspeed enp7s0}
${template4}├${color1}↓${color2}${template2}${downspeed enp7s0}
${color5}${template4}├ ${color4}${template2}Connections ${color6} In ${color2}${tcp_portmon 1 32767 count}${color5}${alignr 4}Out ${template2}${color2}${tcp_portmon 32768 61000 count}
${lua conky_sync_connections}${lua_parse conky_limit_connections 6 23}
${font}]]
